services:
  spark-master:
    image: pyspark-3.4.0-py3.9-java11
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - SPARK_HOME=/opt/bitnami/spark
      - PATH=$JAVA_HOME/bin:$PATH
    ports:
      - "4041:4041"
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./data:/data
      - ./spark-temp:/tmp/spark-temp
    networks:
      spark-net:
        ipv4_address: 172.22.0.2

  spark-worker-1:
    image: pyspark-3.4.0-py3.9-java11
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - SPARK_HOME=/opt/bitnami/spark
      - PATH=$JAVA_HOME/bin:$PATH
    volumes:
      - ./data:/data
      - ./spark-temp:/tmp/spark-temp
    networks:
      spark-net:
        ipv4_address: 172.22.0.3
    depends_on:
      - spark-master